---
- name: Host website
  hosts: all
  become: yes
  tasks:
    - include: tasks/update_packages.yml
    - include: tasks/deploy_packages.yml
    - include: tasks/deploy_mysl_config.yml
    - include: tasks/deploy_website.yml

...